/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import student.studentRepository.studentiLista;
import kompanija.Kompanija;
import kompanija.kompanijaRepository.KompanijaRepository;
import student.Student;
import ugovor.Ugovor;
import ugovor.ugovorRepository.ugovorRepos;
/**
 *
 * @author mluki
 */
public class KompanijaForma extends javax.swing.JFrame {

    /**
     * Creates new form StudentForma
     */
    public KompanijaForma() {
        initComponents();
    }
    LinkedList<Student> studenti = null;
    public LinkedList<Ugovor> ugovori = null;
    public Kompanija kompanija = null;
    public LinkedList<Kompanija> kompanije = null;
    public Student student = null;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtImeKomp = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKompanije = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime kompanije:");

        btnFilter.setText("FILTRIRAJ");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        tblKompanije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime", "PIB", "Kontakt", "Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKompanije);

        btnSacuvaj.setText("SACUVAJ KOMPANIJU");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(txtImeKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtImeKomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        KompanijaRepository kr = new KompanijaRepository();
        LinkedList<Kompanija> kompanije1 = kr.napraviListu(txtImeKomp.getText());
        TableModel tm=tblKompanije.getModel();
        DefaultTableModel dtm=(DefaultTableModel) tm;
        dtm.setRowCount(0);
        for (Kompanija kompanija1 : kompanije1) {
            Object[] rd = new Object[] {
                kompanija1.getIme(),
                kompanija1.getPib(),
                kompanija1.getKontakt(),
                kompanija1.getMail()
            };
            dtm.addRow(rd);
        }
        kompanije = kompanije1;
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        try {
            Kompanija k = kompanije.get(tblKompanije.getSelectedRow());
            System.out.println(tblKompanije.getSelectedRow());
            this.setVisible(false);
            GlavnaForma.Instance.kompanija = k;
            GlavnaForma.Instance.student = student;
            GlavnaForma.Instance.studenti = studenti;
            GlavnaForma.Instance.getTxtFieldPIB().setText(k.getPib());
            GlavnaForma.Instance.getTxtFieldImeKomp().setText(k.getIme());
            GlavnaForma.Instance.getTxtFieldKontakt().setText(k.getKontakt());
            GlavnaForma.Instance.getTxtFieldMailKomp().setText(k.getMail());
            if(student!=null){
                GlavnaForma.Instance.getTxtFieldIme().setText(student.getIme());
                GlavnaForma.Instance.getTxtFieldPrezime().setText(student.getPrezime());
                GlavnaForma.Instance.getTxtFieldStepenStud().setText(student.getStepenStudija());
                GlavnaForma.Instance.getTxtFieldStudProg().setText(student.getStudijskiProgram());
                GlavnaForma.Instance.getTxtFieldBrInd().setText(student.getIndeks());
                GlavnaForma.Instance.getTxtFieldStudMail().setText(student.getStudentskiMail());
            }
            ugovorRepos ur = new ugovorRepos();
            GlavnaForma.Instance.ugovori = ur.napraviListu(k.getIdKompanije());
            for (Ugovor ugovor : GlavnaForma.Instance.ugovori) {
                System.out.println(ugovor.toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Niste izabrali kompaniju", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KompanijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KompanijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KompanijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KompanijaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KompanijaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKompanije;
    private javax.swing.JTextField txtImeKomp;
    // End of variables declaration//GEN-END:variables
}
