/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.LinkedList;
import javax.swing.JTextField;
import kompanija.Kompanija;
import student.Student;
import ugovor.Ugovor;

/**
 *
 * @author student2
 */
public class GlavnaForma extends javax.swing.JFrame {
    public static GlavnaForma Instance;
    public JTextField txtIme;
    public JTextField txtPrezime;
    public JTextField txtStudProgram;
    public JTextField txtBrInd;
    public JTextField txtStudMail;
    public JTextField txtStepenStud;
    public JTextField txtPIB;
    public JTextField txtImeKomp;
    public JTextField txtKontakt;
    public JTextField txtMailKomp;
    
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        Instance = this;
        txtIme = txtFieldIme;
        txtPrezime = txtFieldPrezime;
        txtBrInd = txtFieldBrInd;
        txtStudProgram = txtFieldStudProg;
        txtStepenStud = txtFieldStepenStud;
        txtStudMail = txtFieldStudMail;
    }
    public LinkedList<Student> studenti = new LinkedList<>();
    public LinkedList<Ugovor> ugovori = null;
    public Kompanija kompanija = null;
    public LinkedList<Kompanija> kompanije = null;
    public Student student = null;
    
    public JTextField getTxtFieldBrInd() {
        return txtFieldBrInd;
    }

    public void setTxtFieldBrInd(JTextField txtFieldBrInd) {
        this.txtFieldBrInd = txtFieldBrInd;
    }

    public JTextField getTxtFieldIme() {
        return txtFieldIme;
    }

    public void setTxtFieldIme(JTextField txtFieldIme) {
        this.txtFieldIme = txtFieldIme;
    }

    public JTextField getTxtFieldImeKomp() {
        return txtFieldImeKomp;
    }

    public void setTxtFieldImeKomp(JTextField txtFieldImeKomp) {
        this.txtFieldImeKomp = txtFieldImeKomp;
    }

    public JTextField getTxtFieldKontakt() {
        return txtFieldKontakt;
    }

    public void setTxtFieldKontakt(JTextField txtFieldKontakt) {
        this.txtFieldKontakt = txtFieldKontakt;
    }

    public JTextField getTxtFieldMailKomp() {
        return txtFieldMailKomp;
    }

    public void setTxtFieldMailKomp(JTextField txtFieldMailKomp) {
        this.txtFieldMailKomp = txtFieldMailKomp;
    }

    public JTextField getTxtFieldPIB() {
        return txtFieldPIB;
    }

    public void setTxtFieldPIB(JTextField txtFieldPIB) {
        this.txtFieldPIB = txtFieldPIB;
    }

    public JTextField getTxtFieldPrezime() {
        return txtFieldPrezime;
    }

    public void setTxtFieldPrezime(JTextField txtFieldPrezime) {
        this.txtFieldPrezime = txtFieldPrezime;
    }

    public JTextField getTxtFieldStepenStud() {
        return txtFieldStepenStud;
    }

    public void setTxtFieldStepenStud(JTextField txtFieldStepenStud) {
        this.txtFieldStepenStud = txtFieldStepenStud;
    }

    public JTextField getTxtFieldStudMail() {
        return txtFieldStudMail;
    }

    public void setTxtFieldStudMail(JTextField txtFieldStudMail) {
        this.txtFieldStudMail = txtFieldStudMail;
    }

    public JTextField getTxtFieldStudProg() {
        return txtFieldStudProg;
    }

    public void setTxtFieldStudProg(JTextField txtFieldStudProg) {
        this.txtFieldStudProg = txtFieldStudProg;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldBrInd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFieldStudMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldStudProg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFieldStepenStud = new javax.swing.JTextField();
        btnIzaberiStud = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtFieldPIB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFieldImeKomp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFieldKontakt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFieldMailKomp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unesi novu praksu");
        setResizable(false);

        jLabel1.setText("Ime studenta: ");

        txtFieldIme.setEditable(false);

        jLabel2.setText("Prezime studenta:");

        txtFieldPrezime.setEditable(false);
        txtFieldPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPrezimeActionPerformed(evt);
            }
        });

        jLabel3.setText("Broj indeksa:");

        txtFieldBrInd.setEditable(false);
        txtFieldBrInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldBrIndActionPerformed(evt);
            }
        });

        jLabel4.setText("Studentski mail:");

        txtFieldStudMail.setEditable(false);
        txtFieldStudMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldStudMailActionPerformed(evt);
            }
        });

        jLabel5.setText("Studijski program:");

        txtFieldStudProg.setEditable(false);

        jLabel6.setText("Stepen studija:");

        txtFieldStepenStud.setEditable(false);

        btnIzaberiStud.setText("Izaberi studenta");
        btnIzaberiStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiStudActionPerformed(evt);
            }
        });

        jLabel7.setText("PIB:");

        txtFieldPIB.setEnabled(false);

        jLabel8.setText("Ime kompanije:");

        txtFieldImeKomp.setEnabled(false);
        txtFieldImeKomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldImeKompActionPerformed(evt);
            }
        });

        jLabel9.setText("Kontakt:");

        txtFieldKontakt.setEnabled(false);

        jLabel10.setText("Mail:");

        txtFieldMailKomp.setEnabled(false);

        jButton1.setText("Izaberi kompaniju");
        jButton1.setMaximumSize(new java.awt.Dimension(115, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(115, 28));
        jButton1.setPreferredSize(new java.awt.Dimension(115, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFieldPIB)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFieldImeKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldMailKomp, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(272, 272, 272)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFieldPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtFieldKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFieldImeKomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtFieldMailKomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtFieldIme))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldStudMail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldBrInd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldStudProg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldStepenStud, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnIzaberiStud, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtFieldBrInd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtFieldStudProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtFieldStudMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtFieldStepenStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnIzaberiStud, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPrezimeActionPerformed

    private void txtFieldBrIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldBrIndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldBrIndActionPerformed

    private void txtFieldStudMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldStudMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldStudMailActionPerformed

    private void txtFieldImeKompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldImeKompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldImeKompActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KompanijaForma kf = new KompanijaForma();
        kf.setVisible(true);
        kf.student=student;
        kf.studenti = studenti;
        //setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIzaberiStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiStudActionPerformed
        // TODO add your handling code here:
        StudentForma sf = new StudentForma();
        sf.kompanija = kompanija;
        sf.kompanije = kompanije;
        sf.ugovori = ugovori;
        sf.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnIzaberiStudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiStud;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtFieldBrInd;
    private javax.swing.JTextField txtFieldIme;
    private javax.swing.JTextField txtFieldImeKomp;
    private javax.swing.JTextField txtFieldKontakt;
    private javax.swing.JTextField txtFieldMailKomp;
    private javax.swing.JTextField txtFieldPIB;
    private javax.swing.JTextField txtFieldPrezime;
    private javax.swing.JTextField txtFieldStepenStud;
    private javax.swing.JTextField txtFieldStudMail;
    private javax.swing.JTextField txtFieldStudProg;
    // End of variables declaration//GEN-END:variables
}
